Rename temperature bc

diff --git a/tutorials/CHT/flow-over-plate/buoyantPimpleFoam-laplacianFoam/Allrun_parallel b/tutorials/CHT/flow-over-plate/buoyantPimpleFoam-laplacianFoam/Allrun_parallel
--- a/tutorials/CHT/flow-over-plate/buoyantPimpleFoam-laplacianFoam/Allrun_parallel
+++ b/tutorials/CHT/flow-over-plate/buoyantPimpleFoam-laplacianFoam/Allrun_parallel
@@ -1,12 +1,19 @@
-#!/bin/bash
+#!/bin/bash -xe
 
-# This script prepares and runs all the participants in one terminal, in serial,
-# in parallel (MPI),
-# forwarding the solvers' output to log files.
-# Alternatively, you may execute the scripts "runSolid" and "runFluid"
-# in separate terminals.
+cd "${0%/*}" || exit                                # Run from this directory
+. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
 
-# The script "Allclean" cleans-up the result and log files.
+# clean up
+./Allclean
+
+# Restore initial fields
+cd Fluid
+restore0Dir
+
+cd ../Solid
+restore0Dir
+
+cd ..
 
 # Participant 1: Fluid
 Participant1="Fluid"
